[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/naelle-frega/prisesdeparoles/index.html"
to = "/equipe/naelle-frega/prisesdeparoles/"

[[redirects]]
from = "/equipe-editoriale/index.html"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/projets/index.html"
to = "/realisations/"

[[redirects]]
from = "/actualites/index.html"
to = "/prisesdeparoles/"

[[redirects]]
from = "/naelle-frega/index.html"
to = "/equipe/naelle-frega/"

